# This is a test workflow that is triggered on each push and PR

name: Test frontend and backend

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate docker config file
      run: |
        sudo sysctl -w kernel.unprivileged_userns_clone=1
        DOMAIN=backend \
        SMTP_HOST="" \
        TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL=false \
        INSTALL_DEV=true \
        docker-compose -f docker-compose.yml config | sed 's/app-db-data/app-db-test-data/g;' > docker-stack.yml 
      
    - name: Build frontend image
      run: docker-compose -f docker-stack.yml build frontend

    - name: Build backend image
      run: docker-compose -f docker-stack.yml build backend

    - name: Run backend tests
      run: |
        docker-compose -f docker-stack.yml up -d backend db
        docker-compose -f docker-stack.yml exec -T backend bash /app/tests-start.sh "$@"

    - name: Remove containers and volumes
      run: docker-compose -f docker-stack.yml down -v --remove-orphans
      
